version: '3'
services:
  backend:
      build:
        context: ..
        dockerfile: DRF_practice/Dockerfile
      command: python3 manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      depends_on:
        - db
  db:
    image: postgres:12.11
    environment:
      POSTGRES_DB: "drf"
      POSTGRES_USER: "drfuser"
      POSTGRES_PASSWORD: "123"
      POSTGRES_HOST: "127.0.0.1"
    ports:
      - "5432:5432"